package com.github.ycyz.starrocks.datagrip.format

import com.github.ycyz.starrocks.datagrip.lang.StarRocksElementTypes
import com.intellij.psi.tree.IElementType
import com.intellij.sql.formatter.SqlFormatterHelper
import com.intellij.sql.formatter.model.SqlBlock
import com.intellij.sql.formatter.model.SqlCreateTableBlock
import com.intellij.sql.formatter.model.SqlFunctionCallBlock
import com.intellij.sql.formatter.model.SqlPostfixClauseBlock
import com.intellij.sql.formatter.model.SqlQueryBlock
import com.intellij.sql.formatter.model.SqlStatementBlock
import com.intellij.sql.formatter.model.SqlUnsortedBlock
import com.intellij.sql.formatter.model.SqlViewBlock
import com.intellij.sql.psi.SqlCompositeElementTypes
import kotlin.reflect.KFunction0

class StarRocksFormatterHelper : SqlFormatterHelper {
    override val basicBlockCreation: Map<IElementType, KFunction0<out SqlBlock>> =
        mapOf(
            SqlCompositeElementTypes.SQL_SELECT_STATEMENT to ::SqlQueryBlock,
            SqlCompositeElementTypes.SQL_INSERT_STATEMENT to ::SqlStatementBlock,
            SqlCompositeElementTypes.SQL_UPDATE_STATEMENT to ::SqlStatementBlock,
            SqlCompositeElementTypes.SQL_DELETE_STATEMENT to ::SqlStatementBlock,
            SqlCompositeElementTypes.SQL_MERGE_STATEMENT to ::SqlStatementBlock,
            SqlCompositeElementTypes.SQL_CREATE_TABLE_STATEMENT to ::SqlCreateTableBlock,
            SqlCompositeElementTypes.SQL_CREATE_CATALOG_STATEMENT to ::SqlStatementBlock,
            SqlCompositeElementTypes.SQL_CREATE_SCHEMA_STATEMENT to ::SqlStatementBlock,
            SqlCompositeElementTypes.SQL_CREATE_INDEX_STATEMENT to ::SqlStatementBlock,
            SqlCompositeElementTypes.SQL_ALTER_SCHEMA_STATEMENT to ::SqlStatementBlock,
            SqlCompositeElementTypes.SQL_ALTER_TABLE_STATEMENT to ::SqlStatementBlock,
            SqlCompositeElementTypes.SQL_ALTER_VIEW_STATEMENT to ::SqlStatementBlock,
            SqlCompositeElementTypes.SQL_ALTER_CATALOG_STATEMENT to ::SqlStatementBlock,
            SqlCompositeElementTypes.SQL_CALL_STATEMENT to ::SqlStatementBlock,
            SqlCompositeElementTypes.SQL_START_TRANSACTION_STATEMENT to ::SqlStatementBlock,
            SqlCompositeElementTypes.SQL_COMMIT_STATEMENT to ::SqlStatementBlock,
            SqlCompositeElementTypes.SQL_ROLLBACK_STATEMENT to ::SqlStatementBlock,
            SqlCompositeElementTypes.SQL_TRUNCATE_TABLE_STATEMENT to ::SqlStatementBlock,
            StarRocksElementTypes.TABLE_DDL_STATEMENT to ::SqlCreateTableBlock,
            SqlCompositeElementTypes.SQL_CREATE_VIEW_STATEMENT to ::SqlViewBlock,
            SqlCompositeElementTypes.SQL_CREATE_MATERIALIZED_VIEW_STATEMENT to ::SqlViewBlock,
            StarRocksElementTypes.VIEW_STATEMENT to ::SqlViewBlock,
            StarRocksElementTypes.MATERIALIZED_VIEW_STATEMENT to ::SqlViewBlock,
            StarRocksElementTypes.USER_STATEMENT to ::SqlStatementBlock,
            StarRocksElementTypes.CREATE_USER_STATEMENT to ::SqlStatementBlock,
            StarRocksElementTypes.ALTER_USER_STATEMENT to ::SqlStatementBlock,
            StarRocksElementTypes.DROP_USER_STATEMENT to ::SqlStatementBlock,
            StarRocksElementTypes.ROLE_STATEMENT to ::SqlStatementBlock,
            StarRocksElementTypes.CREATE_ROLE_STATEMENT to ::SqlStatementBlock,
            StarRocksElementTypes.ALTER_ROLE_STATEMENT to ::SqlStatementBlock,
            StarRocksElementTypes.DROP_ROLE_STATEMENT to ::SqlStatementBlock,
            StarRocksElementTypes.SET_PASSWORD_STATEMENT to ::SqlStatementBlock,
            StarRocksElementTypes.GRANT_STATEMENT to ::SqlStatementBlock,
            StarRocksElementTypes.REVOKE_STATEMENT to ::SqlStatementBlock,
            StarRocksElementTypes.SECURITY_PRINCIPAL to ::SqlUnsortedBlock,
            StarRocksElementTypes.PRIVILEGE_LIST to ::SqlUnsortedBlock,
            StarRocksElementTypes.PRIVILEGE_TARGET to ::SqlUnsortedBlock,
            StarRocksElementTypes.SCHEMA_STATEMENT to ::SqlStatementBlock,
            StarRocksElementTypes.INDEX_STATEMENT to ::SqlStatementBlock,
            StarRocksElementTypes.ANALYZE_STATEMENT to ::SqlStatementBlock,
            StarRocksElementTypes.DESCRIBE_STATEMENT to ::SqlStatementBlock,
            StarRocksElementTypes.SELECT_CLAUSE to ::SqlUnsortedBlock,
            StarRocksElementTypes.FROM_CLAUSE to ::SqlUnsortedBlock,
            StarRocksElementTypes.WHERE_CLAUSE to ::SqlUnsortedBlock,
            StarRocksElementTypes.GROUP_BY_CLAUSE to ::SqlUnsortedBlock,
            StarRocksElementTypes.HAVING_CLAUSE to ::SqlUnsortedBlock,
            SqlCompositeElementTypes.SQL_QUALIFY_CLAUSE to ::SqlUnsortedBlock,
            StarRocksElementTypes.QUALIFY_CLAUSE to ::SqlUnsortedBlock,
            StarRocksElementTypes.WINDOW_CLAUSE to ::SqlUnsortedBlock,
            StarRocksElementTypes.ORDER_BY_CLAUSE to ::SqlUnsortedBlock,
            StarRocksElementTypes.LIMIT_CLAUSE to ::SqlUnsortedBlock,
            StarRocksElementTypes.SET_OPERATION_CLAUSE to ::SqlUnsortedBlock,
            StarRocksElementTypes.SELECT_ITEM to ::SqlUnsortedBlock,
            StarRocksElementTypes.ANALYTIC_CLAUSE to ::SqlPostfixClauseBlock,
            StarRocksElementTypes.INSERT_TARGET_CLAUSE to ::SqlUnsortedBlock,
            StarRocksElementTypes.DML_TARGET_TABLE to ::SqlUnsortedBlock,
            StarRocksElementTypes.SET_CLAUSE to ::SqlUnsortedBlock,
            StarRocksElementTypes.SET_ASSIGNMENT to ::SqlUnsortedBlock,
            StarRocksElementTypes.MERGE_USING_CLAUSE to ::SqlUnsortedBlock,
            StarRocksElementTypes.MERGE_ON_CLAUSE to ::SqlUnsortedBlock,
            StarRocksElementTypes.MERGE_WHEN_CLAUSE to ::SqlUnsortedBlock,
            StarRocksElementTypes.TABLE_EXPRESSION to ::SqlUnsortedBlock,
            StarRocksElementTypes.TABLE_REFERENCE to ::SqlUnsortedBlock,
            StarRocksElementTypes.JOIN_EXPRESSION to ::SqlUnsortedBlock,
            StarRocksElementTypes.PARENTHESIZED_JOIN_EXPRESSION to ::SqlUnsortedBlock,
            StarRocksElementTypes.JOIN_CONDITION_CLAUSE to ::SqlUnsortedBlock,
            StarRocksElementTypes.USING_CLAUSE to ::SqlUnsortedBlock,
            StarRocksElementTypes.PREDICATE_EXPRESSION to ::SqlUnsortedBlock,
            StarRocksElementTypes.ORDERING_ITEM to ::SqlUnsortedBlock,
            StarRocksElementTypes.GROUPING_ITEM to ::SqlUnsortedBlock,
            SqlCompositeElementTypes.SQL_FUNCTION_CALL to ::SqlFunctionCallBlock,
            StarRocksElementTypes.FUNCTION_CALL to ::SqlFunctionCallBlock,
            SqlCompositeElementTypes.SQL_TYPE_ELEMENT to ::SqlUnsortedBlock,
            StarRocksElementTypes.CAST_TYPE to ::SqlUnsortedBlock,
            StarRocksElementTypes.DATA_TYPE to ::SqlUnsortedBlock,
            StarRocksElementTypes.TABLE_COLUMN_LIST to ::SqlUnsortedBlock,
            StarRocksElementTypes.COLUMN_DEFINITION to ::SqlUnsortedBlock,
            StarRocksElementTypes.KEY_MODEL_CLAUSE to ::SqlUnsortedBlock,
            StarRocksElementTypes.KEY_COLUMN to ::SqlUnsortedBlock,
            StarRocksElementTypes.COMMENT_CLAUSE to ::SqlUnsortedBlock,
            StarRocksElementTypes.PARTITION_CLAUSE to ::SqlUnsortedBlock,
            StarRocksElementTypes.PARTITION_EXPRESSION to ::SqlUnsortedBlock,
            StarRocksElementTypes.DISTRIBUTION_CLAUSE to ::SqlUnsortedBlock,
            StarRocksElementTypes.DISTRIBUTION_EXPRESSION to ::SqlUnsortedBlock,
            StarRocksElementTypes.BUCKETS_CLAUSE to ::SqlUnsortedBlock,
            StarRocksElementTypes.REFRESH_CLAUSE to ::SqlUnsortedBlock,
            StarRocksElementTypes.PROPERTIES_CLAUSE to ::SqlUnsortedBlock,
            StarRocksElementTypes.PROPERTY_PAIR to ::SqlUnsortedBlock,
            StarRocksElementTypes.RESOURCE_REFERENCE to ::SqlUnsortedBlock,
            StarRocksElementTypes.ANALYZE_TARGET to ::SqlUnsortedBlock,
            StarRocksElementTypes.ANALYZE_COLUMN_LIST to ::SqlUnsortedBlock,
            StarRocksElementTypes.ANALYZE_HISTOGRAM_CLAUSE to ::SqlUnsortedBlock,
            StarRocksElementTypes.DESCRIBE_TARGET to ::SqlUnsortedBlock,
            StarRocksElementTypes.USE_TARGET to ::SqlUnsortedBlock
        )
}
