package com.github.ycyz.starrocks.datagrip.dialect

object StarRocksFunctionCatalog {
    val FUNCTIONS: List<StarRocksFunctionSignature> = listOf(
        StarRocksFunctionSignature("ACOS", StarRocksFunctionCategory.MATH, "ACOS(x)", "Returns the arc cosine."),
        StarRocksFunctionSignature("ABS", StarRocksFunctionCategory.MATH, "ABS(number)", "Returns the absolute value."),
        StarRocksFunctionSignature("APPROX_COUNT_DISTINCT", StarRocksFunctionCategory.AGGREGATE, "APPROX_COUNT_DISTINCT(expr)", "Returns an approximate distinct count."),
        StarRocksFunctionSignature("ARRAY_AGG", StarRocksFunctionCategory.AGGREGATE, "ARRAY_AGG(expr)", "Aggregates values into an array."),
        StarRocksFunctionSignature("ARRAY_CONTAINS", StarRocksFunctionCategory.ARRAY, "ARRAY_CONTAINS(array, element)", "Checks whether an array contains an element."),
        StarRocksFunctionSignature("ARRAY_DISTINCT", StarRocksFunctionCategory.ARRAY, "ARRAY_DISTINCT(array)", "Removes duplicate array elements."),
        StarRocksFunctionSignature("AVG", StarRocksFunctionCategory.AGGREGATE, "AVG(expr)", "Returns the average value."),
        StarRocksFunctionSignature("CAST", StarRocksFunctionCategory.TYPE_CONVERSION, "CAST(expr AS type)", "Converts an expression to another type."),
        StarRocksFunctionSignature("CEIL", StarRocksFunctionCategory.MATH, "CEIL(x)", "Rounds up to the nearest integer."),
        StarRocksFunctionSignature("CEILING", StarRocksFunctionCategory.MATH, "CEILING(x)", "Rounds up to the nearest integer."),
        StarRocksFunctionSignature("CONCAT", StarRocksFunctionCategory.STRING, "CONCAT(str, ...)", "Concatenates strings."),
        StarRocksFunctionSignature("COALESCE", StarRocksFunctionCategory.CONDITIONAL, "COALESCE(expr, ...)", "Returns the first non-null expression."),
        StarRocksFunctionSignature("CONCAT_WS", StarRocksFunctionCategory.STRING, "CONCAT_WS(separator, str, ...)", "Concatenates strings with a separator."),
        StarRocksFunctionSignature("CONV", StarRocksFunctionCategory.TYPE_CONVERSION, "CONV(number, from_base, to_base)", "Converts a number between bases."),
        StarRocksFunctionSignature("COS", StarRocksFunctionCategory.MATH, "COS(x)", "Returns the cosine."),
        StarRocksFunctionSignature("COUNT", StarRocksFunctionCategory.AGGREGATE, "COUNT(expr)", "Returns the number of rows or values."),
        StarRocksFunctionSignature("DATE_TRUNC", StarRocksFunctionCategory.DATE_TIME, "DATE_TRUNC(unit, date)", "Truncates a date or datetime value."),
        StarRocksFunctionSignature("DATEDIFF", StarRocksFunctionCategory.DATE_TIME, "DATEDIFF(date1, date2)", "Returns the date difference."),
        StarRocksFunctionSignature("DATE_ADD", StarRocksFunctionCategory.DATE_TIME, "DATE_ADD(date, INTERVAL expr unit)", "Adds an interval to a date."),
        StarRocksFunctionSignature("DATE_FORMAT", StarRocksFunctionCategory.DATE_TIME, "DATE_FORMAT(date, format)", "Formats a date or datetime value."),
        StarRocksFunctionSignature("DATE_SUB", StarRocksFunctionCategory.DATE_TIME, "DATE_SUB(date, INTERVAL expr unit)", "Subtracts an interval from a date."),
        StarRocksFunctionSignature("DENSE_RANK", StarRocksFunctionCategory.ANALYTIC, "DENSE_RANK() OVER (...)", "Returns dense rank in a window."),
        StarRocksFunctionSignature("ELEMENT_AT", StarRocksFunctionCategory.ARRAY, "ELEMENT_AT(array, index)", "Returns an array element."),
        StarRocksFunctionSignature("EXP", StarRocksFunctionCategory.MATH, "EXP(x)", "Returns e raised to x."),
        StarRocksFunctionSignature("FIRST_VALUE", StarRocksFunctionCategory.ANALYTIC, "FIRST_VALUE(expr) OVER (...)", "Returns the first window value."),
        StarRocksFunctionSignature("FLOOR", StarRocksFunctionCategory.MATH, "FLOOR(x)", "Rounds down to the nearest integer."),
        StarRocksFunctionSignature("FROM_UNIXTIME", StarRocksFunctionCategory.DATE_TIME, "FROM_UNIXTIME(timestamp)", "Converts a Unix timestamp to datetime."),
        StarRocksFunctionSignature("GET_JSON_DOUBLE", StarRocksFunctionCategory.JSON, "GET_JSON_DOUBLE(json, path)", "Extracts a double from JSON."),
        StarRocksFunctionSignature("GET_JSON_INT", StarRocksFunctionCategory.JSON, "GET_JSON_INT(json, path)", "Extracts an integer from JSON."),
        StarRocksFunctionSignature("GET_JSON_STRING", StarRocksFunctionCategory.JSON, "GET_JSON_STRING(json, path)", "Extracts a string from JSON."),
        StarRocksFunctionSignature("HLL_HASH", StarRocksFunctionCategory.HLL, "HLL_HASH(expr)", "Hashes a value for HLL aggregation."),
        StarRocksFunctionSignature("HLL_UNION", StarRocksFunctionCategory.HLL, "HLL_UNION(hll)", "Unions HLL values."),
        StarRocksFunctionSignature("HLL_UNION_AGG", StarRocksFunctionCategory.HLL, "HLL_UNION_AGG(hll)", "Aggregates HLL values."),
        StarRocksFunctionSignature("IF", StarRocksFunctionCategory.CONDITIONAL, "IF(condition, true_value, false_value)", "Returns one of two values."),
        StarRocksFunctionSignature("IFNULL", StarRocksFunctionCategory.CONDITIONAL, "IFNULL(expr, fallback)", "Returns fallback when expr is null."),
        StarRocksFunctionSignature("JSON_ARRAY", StarRocksFunctionCategory.JSON, "JSON_ARRAY(value, ...)", "Creates a JSON array."),
        StarRocksFunctionSignature("JSON_EXISTS", StarRocksFunctionCategory.JSON, "JSON_EXISTS(json, path)", "Checks whether a JSON path exists."),
        StarRocksFunctionSignature("JSON_OBJECT", StarRocksFunctionCategory.JSON, "JSON_OBJECT(key, value, ...)", "Creates a JSON object."),
        StarRocksFunctionSignature("JSON_QUERY", StarRocksFunctionCategory.JSON, "JSON_QUERY(json, path)", "Extracts a JSON value."),
        StarRocksFunctionSignature("JSON_STRING", StarRocksFunctionCategory.JSON, "JSON_STRING(json)", "Converts JSON to string."),
        StarRocksFunctionSignature("JSON_VALUE", StarRocksFunctionCategory.JSON, "JSON_VALUE(json, path)", "Extracts a scalar JSON value."),
        StarRocksFunctionSignature("LAG", StarRocksFunctionCategory.ANALYTIC, "LAG(expr) OVER (...)", "Returns a previous window value."),
        StarRocksFunctionSignature("LAST_DAY", StarRocksFunctionCategory.DATE_TIME, "LAST_DAY(date)", "Returns the last day of the month."),
        StarRocksFunctionSignature("LAST_VALUE", StarRocksFunctionCategory.ANALYTIC, "LAST_VALUE(expr) OVER (...)", "Returns the last window value."),
        StarRocksFunctionSignature("LEAD", StarRocksFunctionCategory.ANALYTIC, "LEAD(expr) OVER (...)", "Returns a following window value."),
        StarRocksFunctionSignature("LENGTH", StarRocksFunctionCategory.STRING, "LENGTH(str)", "Returns string length."),
        StarRocksFunctionSignature("LIKE", StarRocksFunctionCategory.PREDICATE, "expr LIKE pattern", "Matches a string pattern."),
        StarRocksFunctionSignature("LN", StarRocksFunctionCategory.MATH, "LN(x)", "Returns the natural logarithm."),
        StarRocksFunctionSignature("LOG", StarRocksFunctionCategory.MATH, "LOG(base, x)", "Returns a logarithm."),
        StarRocksFunctionSignature("LOWER", StarRocksFunctionCategory.STRING, "LOWER(str)", "Converts a string to lower case."),
        StarRocksFunctionSignature("LPAD", StarRocksFunctionCategory.STRING, "LPAD(str, len, pad)", "Left pads a string."),
        StarRocksFunctionSignature("LTRIM", StarRocksFunctionCategory.STRING, "LTRIM(str)", "Trims leading spaces."),
        StarRocksFunctionSignature("MD5", StarRocksFunctionCategory.ENCRYPTION, "MD5(str)", "Returns the MD5 hash."),
        StarRocksFunctionSignature("MAX", StarRocksFunctionCategory.AGGREGATE, "MAX(expr)", "Returns the maximum value."),
        StarRocksFunctionSignature("MIN", StarRocksFunctionCategory.AGGREGATE, "MIN(expr)", "Returns the minimum value."),
        StarRocksFunctionSignature("NTILE", StarRocksFunctionCategory.ANALYTIC, "NTILE(n) OVER (...)", "Distributes rows into buckets."),
        StarRocksFunctionSignature("NULLIF", StarRocksFunctionCategory.CONDITIONAL, "NULLIF(expr1, expr2)", "Returns null when two expressions are equal."),
        StarRocksFunctionSignature("PARSE_URL", StarRocksFunctionCategory.URL, "PARSE_URL(url, part)", "Extracts a URL component."),
        StarRocksFunctionSignature("PERCENT_RANK", StarRocksFunctionCategory.ANALYTIC, "PERCENT_RANK() OVER (...)", "Returns percent rank."),
        StarRocksFunctionSignature("POW", StarRocksFunctionCategory.MATH, "POW(x, y)", "Returns x raised to y."),
        StarRocksFunctionSignature("POWER", StarRocksFunctionCategory.MATH, "POWER(x, y)", "Returns x raised to y."),
        StarRocksFunctionSignature("RANDOM", StarRocksFunctionCategory.MATH, "RANDOM()", "Returns a random value."),
        StarRocksFunctionSignature("RANK", StarRocksFunctionCategory.ANALYTIC, "RANK() OVER (...)", "Returns the rank in a window."),
        StarRocksFunctionSignature("REGEXP", StarRocksFunctionCategory.PREDICATE, "expr REGEXP pattern", "Matches a regular expression."),
        StarRocksFunctionSignature("REPLACE", StarRocksFunctionCategory.STRING, "REPLACE(str, from, to)", "Replaces substrings."),
        StarRocksFunctionSignature("ROUND", StarRocksFunctionCategory.MATH, "ROUND(x, d)", "Rounds a number."),
        StarRocksFunctionSignature("ROW_NUMBER", StarRocksFunctionCategory.ANALYTIC, "ROW_NUMBER() OVER (...)", "Returns the row number in a window."),
        StarRocksFunctionSignature("RPAD", StarRocksFunctionCategory.STRING, "RPAD(str, len, pad)", "Right pads a string."),
        StarRocksFunctionSignature("RTRIM", StarRocksFunctionCategory.STRING, "RTRIM(str)", "Trims trailing spaces."),
        StarRocksFunctionSignature("SHA2", StarRocksFunctionCategory.ENCRYPTION, "SHA2(str, bits)", "Returns a SHA-2 hash."),
        StarRocksFunctionSignature("SIN", StarRocksFunctionCategory.MATH, "SIN(x)", "Returns the sine."),
        StarRocksFunctionSignature("SUM", StarRocksFunctionCategory.AGGREGATE, "SUM(expr)", "Returns the sum of values."),
        StarRocksFunctionSignature("SUBSTR", StarRocksFunctionCategory.STRING, "SUBSTR(str, pos, len)", "Returns a substring."),
        StarRocksFunctionSignature("SUBSTRING", StarRocksFunctionCategory.STRING, "SUBSTRING(str, pos, len)", "Returns a substring."),
        StarRocksFunctionSignature("TAN", StarRocksFunctionCategory.MATH, "TAN(x)", "Returns the tangent."),
        StarRocksFunctionSignature("TIMESTAMPDIFF", StarRocksFunctionCategory.DATE_TIME, "TIMESTAMPDIFF(unit, start, end)", "Returns a timestamp difference."),
        StarRocksFunctionSignature("TO_BITMAP", StarRocksFunctionCategory.BITMAP, "TO_BITMAP(expr)", "Converts a value to bitmap."),
        StarRocksFunctionSignature("TO_DATE", StarRocksFunctionCategory.DATE_TIME, "TO_DATE(datetime)", "Converts datetime to date."),
        StarRocksFunctionSignature("TO_JSON", StarRocksFunctionCategory.JSON, "TO_JSON(value)", "Converts a value to JSON."),
        StarRocksFunctionSignature("TRIM", StarRocksFunctionCategory.STRING, "TRIM(str)", "Trims spaces."),
        StarRocksFunctionSignature("UNIX_TIMESTAMP", StarRocksFunctionCategory.DATE_TIME, "UNIX_TIMESTAMP(date)", "Converts datetime to Unix timestamp."),
        StarRocksFunctionSignature("UPPER", StarRocksFunctionCategory.STRING, "UPPER(str)", "Converts a string to upper case."),
        StarRocksFunctionSignature("UUID", StarRocksFunctionCategory.STRING, "UUID()", "Returns a UUID string."),
        StarRocksFunctionSignature("WEEK", StarRocksFunctionCategory.DATE_TIME, "WEEK(date)", "Returns the week number."),
        StarRocksFunctionSignature("YEAR", StarRocksFunctionCategory.DATE_TIME, "YEAR(date)", "Returns the year."),
        StarRocksFunctionSignature("BITMAP_UNION", StarRocksFunctionCategory.BITMAP, "BITMAP_UNION(bitmap)", "Unions bitmap values."),
        StarRocksFunctionSignature("BITMAP_UNION_INT", StarRocksFunctionCategory.BITMAP, "BITMAP_UNION_INT(expr)", "Aggregates integer values into a bitmap union."),
        StarRocksFunctionSignature("ARRAY_LENGTH", StarRocksFunctionCategory.ARRAY, "ARRAY_LENGTH(array)", "Returns the number of array elements."),
        StarRocksFunctionSignature("UNNEST", StarRocksFunctionCategory.TABLE, "UNNEST(array)", "Expands an array as a table function.")
    )

    val BUILTIN_FUNCTION_NAMES: Set<String> = buildSet {
        addAll(StarRocksBuiltinFunctionNames.NAMES)
        addAll(FUNCTIONS.map { it.lookupName })
    }

    private val byName = FUNCTIONS.associateBy { it.lookupName }

    fun find(name: String): StarRocksFunctionSignature? = byName[name.uppercase()]
}
