package com.github.ycyz.starrocks.datagrip.dialect

import com.github.ycyz.starrocks.datagrip.completion.FunctionMetadata

object StarRocksFunctionRegistry {
    // Function names are intended to track StarRocks official docs/source, not adjacent SQL dialects.
    private val functionMetadata = listOf(
        // Aggregate and analytic functions.
        aggregate("ANY_VALUE"),
        aggregate("APPROX_COUNT_DISTINCT"),
        aggregate("AVG"),
        aggregate("BITMAP_AGG"),
        aggregate("BITMAP_AND"),
        aggregate("BITMAP_AND_COUNT"),
        aggregate("BITMAP_OR"),
        aggregate("BITMAP_OR_COUNT"),
        aggregate("BITMAP_UNION"),
        aggregate("BITMAP_UNION_COUNT"),
        aggregate("BITMAP_XOR"),
        aggregate("BITMAP_XOR_COUNT"),
        aggregate("COUNT"),
        aggregate("COUNT_IF"),
        analytic("DENSE_RANK"),
        analytic("FIRST_VALUE"),
        aggregate("GROUP_CONCAT"),
        aggregate("GROUPING"),
        aggregate("GROUPING_ID"),
        aggregate("HLL_UNION_AGG"),
        analytic("LAG"),
        analytic("LAST_VALUE"),
        analytic("LEAD"),
        aggregate("MAX"),
        aggregate("MIN"),
        aggregate("MEDIAN"),
        analytic("NTILE"),
        aggregate("PERCENTILE_APPROX"),
        aggregate("PERCENTILE_CONT"),
        aggregate("PERCENTILE_DISC"),
        analytic("PERCENT_RANK"),
        analytic("RANK"),
        analytic("ROW_NUMBER"),
        aggregate("STDDEV"),
        aggregate("STDDEV_POP"),
        aggregate("STDDEV_SAMP"),
        aggregate("SUM"),
        aggregate("VARIANCE"),
        aggregate("VAR_POP"),
        aggregate("VAR_SAMP"),

        // String functions.
        string("ASCII"),
        string("BIN"),
        string("CHAR_LENGTH"),
        string("CHARACTER_LENGTH"),
        string("CONCAT"),
        string("CONCAT_WS"),
        string("ELT"),
        string("ENDS_WITH"),
        string("FIELD"),
        string("FIND_IN_SET"),
        string("FROM_BASE64"),
        string("HEX"),
        string("INSTR"),
        string("INITCAP"),
        string("LEFT"),
        string("LENGTH"),
        string("LOCATE"),
        string("LOWER"),
        string("LPAD"),
        string("LTRIM"),
        string("MONEY_FORMAT"),
        string("NULL_OR_EMPTY"),
        string("POSITION"),
        string("REGEXP"),
        string("REGEXP_EXTRACT"),
        string("REGEXP_REPLACE"),
        string("REPLACE"),
        string("REPEAT"),
        string("REVERSE"),
        string("RIGHT"),
        string("RPAD"),
        string("RTRIM"),
        string("SHA1"),
        string("SHA2"),
        string("SPLIT"),
        string("SPLIT_PART"),
        string("STARTS_WITH"),
        string("STRCMP"),
        string("SUBSTR"),
        string("SUBSTRING"),
        string("TO_BASE64"),
        string("TRIM"),
        string("MD5"),
        string("UNHEX"),
        string("UPPER"),

        // Date and time functions.
        dateTime("ADDDATE"),
        dateTime("CURDATE"),
        dateTime("CURTIME"),
        dateTime("CURRENT_DATE"),
        dateTime("CURRENT_TIME"),
        dateTime("CURRENT_TIMESTAMP"),
        dateTime("DATE"),
        dateTime("DATE_ADD"),
        dateTime("DATE_DIFF"),
        dateTime("DATE_FORMAT"),
        dateTime("DATE_SUB"),
        dateTime("DATE_TRUNC"),
        dateTime("DATEDIFF"),
        dateTime("DAY"),
        dateTime("DAYNAME"),
        dateTime("DAYOFMONTH"),
        dateTime("DAYOFWEEK"),
        dateTime("DAYOFYEAR"),
        dateTime("FROM_DAYS"),
        dateTime("FROM_UNIXTIME"),
        dateTime("HOUR"),
        dateTime("LAST_DAY"),
        dateTime("MAKEDATE"),
        dateTime("MINUTE"),
        dateTime("MONTH"),
        dateTime("MONTHNAME"),
        dateTime("NOW"),
        dateTime("QUARTER"),
        dateTime("SECOND"),
        dateTime("STR_TO_DATE"),
        dateTime("SUBDATE"),
        dateTime("TIMEDIFF"),
        dateTime("TIMESTAMP"),
        dateTime("TIMESTAMPADD"),
        dateTime("TIMESTAMPDIFF"),
        dateTime("TIME_SLICE"),
        dateTime("TO_DATE"),
        dateTime("TO_DAYS"),
        dateTime("UNIX_TIMESTAMP"),
        dateTime("UTC_TIMESTAMP"),
        dateTime("WEEK"),
        dateTime("WEEKDAY"),
        dateTime("WEEKOFYEAR"),
        dateTime("YEAR"),

        // Math functions.
        math("ABS"),
        math("ACOS"),
        math("ASIN"),
        math("ATAN"),
        math("ATAN2"),
        math("CBRT"),
        math("CEIL"),
        math("CEILING"),
        math("CONV"),
        math("COS"),
        math("COT"),
        math("DEGREES"),
        math("E"),
        math("EXP"),
        math("FLOOR"),
        math("GREATEST"),
        math("LEAST"),
        math("LN"),
        math("LOG"),
        math("LOG10"),
        math("LOG2"),
        math("MOD"),
        math("NEGATIVE"),
        math("PI"),
        math("PMOD"),
        math("POSITIVE"),
        math("POW"),
        math("POWER"),
        math("RADIANS"),
        math("RAND"),
        math("RANDOM"),
        math("ROUND"),
        math("SIGN"),
        math("SIN"),
        math("SQRT"),
        math("TAN"),
        math("TRUNCATE"),

        // Conditional, conversion, JSON, array, bitmap, and HLL functions.
        array("ARRAY_AGG"),
        array("ARRAY_AVG"),
        array("ARRAY_APPEND"),
        array("ARRAY_CONCAT"),
        array("ARRAY_CONTAINS"),
        array("ARRAY_CONTAINS_ALL"),
        array("ARRAY_CONTAINS_SEQ"),
        array("ARRAY_CUM_SUM"),
        array("ARRAY_DIFFERENCE"),
        array("ARRAY_DISTINCT"),
        array("ARRAY_FILTER"),
        array("ARRAY_FLATTEN"),
        array("ARRAY_GENERATE"),
        array("ARRAY_INTERSECT"),
        array("ARRAY_JOIN"),
        array("ARRAY_LENGTH"),
        array("ARRAY_MAP"),
        array("ARRAY_MAX"),
        array("ARRAY_MIN"),
        array("ARRAY_POSITION"),
        array("ARRAY_REPEAT"),
        array("ARRAY_REMOVE"),
        array("ARRAY_SORT"),
        array("ARRAY_SORTBY"),
        array("ARRAY_SLICE"),
        array("ARRAY_SUM"),
        array("ARRAY_TO_BITMAP"),
        array("ARRAY_TOP_N"),
        array("ARRAY_UNIQUE_AGG"),
        array("ARRAY_UNION"),
        array("ARRAYS_OVERLAP"),
        array("ARRAYS_ZIP"),
        tableFunction("UNNEST"),
        bitmap("BITMAP_COUNT"),
        bitmap("BITMAP_EMPTY"),
        bitmap("BITMAP_FROM_STRING"),
        bitmap("BITMAP_HASH"),
        bitmap("BITMAP_HAS_ANY"),
        bitmap("BITMAP_HAS_ALL"),
        bitmap("BITMAP_INTERSECT"),
        bitmap("BITMAP_MAX"),
        bitmap("BITMAP_MIN"),
        bitmap("BITMAP_TO_ARRAY"),
        bitmap("BITMAP_TO_STRING"),
        bitmap("BITMAP_UNION_INT"),
        scalar("CARDINALITY"),
        scalar("CAST"),
        scalar("COALESCE"),
        scalar("CONVERT"),
        scalar("ELEMENT_AT"),
        json("GET_JSON_DOUBLE"),
        json("GET_JSON_INT"),
        json("GET_JSON_OBJECT"),
        json("GET_JSON_STRING"),
        hll("HLL_CARDINALITY"),
        hll("HLL_EMPTY"),
        hll("HLL_HASH"),
        scalar("IF"),
        scalar("IFNULL"),
        scalar("ISNULL"),
        json("JSON_ARRAY"),
        json("JSON_EXISTS"),
        json("JSON_EXTRACT"),
        json("JSON_KEYS"),
        json("JSON_LENGTH"),
        json("JSON_OBJECT"),
        json("JSON_PRETTY"),
        json("JSON_QUERY"),
        json("JSON_REMOVE"),
        json("JSON_SET"),
        json("JSON_STRING"),
        json("JSON_VALUE"),
        json("PARSE_JSON"),
        map("MAP_CONCAT"),
        map("MAP_FILTER"),
        map("MAP_FROM_ARRAYS"),
        map("MAP_KEYS"),
        map("MAP_SIZE"),
        map("MAP_VALUES"),
        scalar("NULLIF"),
        map("SUM_MAP"),
        bitmap("TO_BITMAP")
    )

    private val functionNames = functionMetadata.mapTo(linkedSetOf()) { it.name }

    fun functions(): List<FunctionMetadata> = functionMetadata

    fun contains(functionName: String): Boolean = functionNames.contains(functionName)

    fun names(): Set<String> = functionNames

    private fun aggregate(name: String): FunctionMetadata = FunctionMetadata(name, "StarRocks aggregate")
    private fun analytic(name: String): FunctionMetadata = FunctionMetadata(name, "StarRocks window")
    private fun array(name: String): FunctionMetadata = FunctionMetadata(name, "StarRocks array")
    private fun bitmap(name: String): FunctionMetadata = FunctionMetadata(name, "StarRocks bitmap")
    private fun dateTime(name: String): FunctionMetadata = FunctionMetadata(name, "StarRocks date/time")
    private fun hll(name: String): FunctionMetadata = FunctionMetadata(name, "StarRocks HLL")
    private fun json(name: String): FunctionMetadata = FunctionMetadata(name, "StarRocks JSON")
    private fun map(name: String): FunctionMetadata = FunctionMetadata(name, "StarRocks map")
    private fun math(name: String): FunctionMetadata = FunctionMetadata(name, "StarRocks math")
    private fun scalar(name: String): FunctionMetadata = FunctionMetadata(name, "StarRocks scalar")
    private fun string(name: String): FunctionMetadata = FunctionMetadata(name, "StarRocks string")
    private fun tableFunction(name: String): FunctionMetadata = FunctionMetadata(name, "StarRocks table function")
}
